# Generated by Django 5.2 on 2026-09-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otpverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
